---
- name: Install Amazon CloudWatch Agent.
  ansible.builtin.yum:
    name: /root/AmazonAgent/amazon-cloudwatch-agent-1.247350.0-1.amzn2.x86_64.rpm
    state: present

- name: Copy a config file to a Amazon CloudWatch Agent
  ansible.builtin.copy:
    src: amazon-cloudwatch-agent.json
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
  when: install_ok_aca is changed
  notify: Restart amazon-cloudwatch-agent  