---
- name: Dowload a cloudwatch/efs-utils for Amazon Linux2
  blocK:
  - name: Make directory to store package for Amazon agent
    file:
      path: /root/AmazonAgent
      state: directory
  - name: Download only to Amazon CloudWatch Agent
    ansible.builtin.yum:
      name: amazon-cloudwatch-agent
      download_dir: /root/AmazonAgent
      download_only: yes
  - name: Download only to Amazon efs-utils
    ansible.builtin.yum:
      name: amazon-efs-utils
      download_dir: /root/AmazonAgent
      download_only: yes

- name: Gather the rpm package facts
  package_facts:
    manager: auto

- name: Install Amazon CloudWatch Agent.
  ansible.builtin.yum:
    name: /root/AmazonAgent/amazon-cloudwatch-agent-1.247350.0-1.amzn2.x86_64.rpm
    state: present
  when: "'amazon-cloudwatch-agent' not in ansible_facts.packages"

- name: Copy a config file to a Amazon CloudWatch Agent
  ansible.builtin.copy:
    src: amazon-cloudwatch-agent.json
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
  when: install_ok_aca is changed
  notify: Restart amazon-cloudwatch-agent  