---
- name: Download onley dependency package to the /root/efs-utils
  block:
    - name: Make directory to download a package
      file:
        path: /root/efs-utils
        state: directory
    - name: Copy efs-utils package to the target server
      ansible.builtin.copy:
        src: amazon-efs-utils-1.33.2-1.el8.noarch.rpm
        dest: /root/efs-utils/amazon-efs-utils-1.33.2-1.el8.noarch.rpm
    - name: Download a dependency package to the efs-utils
      ansible.builtin.shell:
        chdir: /root/efs-utils
        cmd: dnf download amazon-efs-utils-1.33.2-1.el8.noarch.rpm --resolve

#- name: Install AWS CloudWatch from the AWS S3
#  dnf:
#    name: 'https://s3.amazonaws.com/amazoncloudwatch-agent/redhat/amd64/latest/amazon-cloudwatch-agent.rpm'
#    state: present
