---
- name: Download onley dependency package to the /root/efs-utils
  block:
    - name: Make directory to download a package
      file:
        path: /root/efs-utils
        state: directory

    - name: Copy efs-utils package to the target server
      ansible.builtin.copy:
        src: amazon-efs-utils-1.33.2-1.el8.noarch.rpm
        dest: /root/efs-utils/amazon-efs-utils-1.33.2-1.el8.noarch.rpm

    - name: Download a dependency package to the efs-utils
      ansible.builtin.shell:
        chdir: /root/efs-utils
        cmd: dnf download amazon-efs-utils-1.33.2-1.el8.noarch.rpm --resolve

    - name: Download a AWS CloudWatch package
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/redhat/amd64/latest/amazon-cloudwatch-agent.rpm
        dest: /root

- name: Install the AWS CloudWatch package
  block:
    - name: Gather the rpm package facts
      package_facts:
        manager: auto

    - name: Install the AWS CloudWatch package
      dnf:
        name: /root/amazon-cloudwatch-agent.rpm
        state: present
      when: "'amazon-cloudwatch-agent' not in ansible_facts.packages"
      register: install_ok_aca

    - name: Copy a config of aws cloudwatch to aws cloudwatch agent.
      ansible.builtin.copy:
        src: amazon-cloudwatch-agent.json
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
      when: install_ok_aca is changed
      notify: Restart amazon-cloudwatch-agent