---
- name: Install efs-utils from a local file
  dnf:
    name: amazon-efs-utils-1.33.2-1.el8.noarch.rpm
    state: present

- name: Install AWS CloudWatch from the AWS S3
  dnf:
    name: 'https://s3.amazonaws.com/amazoncloudwatch-agent/redhat/amd64/latest/amazon-cloudwatch-agent.rpm'
    state: present
