---
change_permission_files:
  - path: /etc/passwd
    owner: root
    group: root
    mode: '0644' # original 0644
  - path: /etc/shadow
    owner: root
    group: root
    mode: '0000' # original 0000
  - path: /etc/hosts
    owner: root
    group: root
    mode: '0600' # original 0644
  - path: /etc/services
    owner: root
    group: root
    mode: '0640' # original 0644
  - path: /etc/rsyslog.conf
    owner: root
    group: root
    mode: '0640'
  - path: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: '0640' # original 0644
  - path: /etc/exports
    owner: root
    group: root
    mode: '0644' # original 0644

remove_setuid_files:
  - path: /usr/bin/at
  - path: /usr/bin/crontab
  - path: /sbin/dump
  - path: /sbin/restore
  - path: /sbin/unix_chkpwd
  - path: /usr/bin/lpq
  - path: /usr/bin/lpq-lpd
  - path: /usr/bin/lpr
  - path: /usr/bin/lpr-lpd
  - path: /usr/bin/lprm
  - path: /usr/bin/lprm-lpd
  - path: /usr/bin/newgrp
  - path: /usr/sbin/lpc
  - path: /usr/sbin/lpc-lpd
  - path: /usr/sbin/traceroute