---
- name: Enable a repostory for Amazon Linux2 to install nginx
  shell: amazon-linux-extras enable nginx1

- name: populate service facts
  ansible.builtin.service_facts:

- name: Stop/Disable the service if it's defined
  ansible.builtin.systemd:
    name: "{{ service }}"
    state: stopped
    enabled: no
  loop: "{{ stop_services_list }}"
  loop_control:
    loop_var: service
  when: "ansible_facts.services[service] is defined"

- name: Check a process of ftp's server
  shell: pgrep {{ service|lower }} | wc -l
  ignore_errors: false
  changed_when: false
  register: command_result
  failed_when: command_result.stdout|int > 0
  loop: "{{ check_service }}"
  loop_control:
    loop_var: service

# uninstall a package
- name: Gather the rpm package facts
  package_facts:
    manager: auto

# To disable auto update for that is to uninstall packagekit
- name: uninstall a package if it's installed
  ansible.builtin.yum:
    name: "{{ package }}"
    state: absent
  loop: "{{ uninstall_pacakges }}"
  loop_control:
    loop_var: package
  when: "package in ansible_facts.packages"

# - name: Disabling SELinux state
#   ansible.posix.selinux:
#     state: disabled
#   register: selinuxdisabled

# - name: Print the changes in Configuration file
#   command: grep SELINUX /etc/sysconfig/selinux
#   register: selvalue

# - name: Print debug message
#   debug: 
#     var: selvalue.stdout_lines

- name: Install the latest version of security package
  ansible.builtin.yum:
    name:
      - openssl
      - openssl-pkcs11
      - openssh-server
      - openssh-clients
      - openssh
      - sudo
      - ncurses-libs
      - pam
      - passwd
      - pcre2
      - pcre
      - readline
      - shadow-utils
      - kernel
      - systemd
      - systemd-libs
      - zlib
      - xz
      - filesystem
      - unzip
      - xfsprogs
      - expat-devel
      - openssl-devel
    state: latest

- name: Download package only
  block:
    - name: Make directory to store package for nginx
      file:
        path: /root/nginx
        state: directory
    - name: Download only to nginx
      ansible.builtin.yum:
        name: nginx
        download_dir: /root/nginx
        download_only: yes
    - name: Make directory to store package for openjdk
      file:
        path: /root/openjdk
        state: directory
    - name: Download only to openjdk
      ansible.builtin.yum:
        name: java-1.8.0-openjdk-headless
        download_dir: /root/openjdk
        download_only: yes
    - name: Make a directory to store a package for tomcat
      file:
        path: /root/tomcat
        state: directory
    - name: Download a tomcat 9
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz
        dest: /root/tomcat
    - name: Copy a apr library to a tomcat
      ansible.builtin.copy:
        src: apr-1.7.0.amzn2.bin.tar.gz
        dest: /root/tomcat
    - name: Copy a apr-utils library to a tomcat
      ansible.builtin.copy:
        src: apr-util-1.6.1.amzn2.bin.tar.gz
        dest: /root/tomcat
