---
- name: Enable a repostory for Amazon Linux2 to install nginx
  shell: amazon-linux-extras enable nginx1

- name: populate service facts
  ansible.builtin.service_facts:

- name: Stop/Disable the service if it's defined
  ansible.builtin.systemd:
    name: "{{ service }}"
    state: stopped
    enabled: no
  loop: "{{ stop_services_list }}"
  loop_control:
    loop_var: service
  when: "ansible_facts.services[service] is defined"

- name: Check a process of ftp's server
  shell: pgrep {{ service|lower }} | wc -l
  ignore_errors: false
  changed_when: false
  register: command_result
  failed_when: command_result.stdout|int > 0
  loop: "{{ check_service }}"
  loop_control:
    loop_var: service

# uninstall a package
- name: Gather the rpm package facts
  package_facts:
    manager: auto

# To disable auto update for that is to uninstall packagekit
- name: uninstall a package if it's installed
  ansible.builtin.yum:
    name: "{{ package }}"
    state: absent
  loop: "{{ uninstall_pacakges }}"
  loop_control:
    loop_var: package
  when: "package in ansible_facts.packages"

# - name: Disabling SELinux state
#   ansible.posix.selinux:
#     state: disabled
#   register: selinuxdisabled

# - name: Print the changes in Configuration file
#   command: grep SELINUX /etc/sysconfig/selinux
#   register: selvalue

# - name: Print debug message
#   debug: 
#     var: selvalue.stdout_lines

- name: Install the latest version of security package
  ansible.builtin.yum:
    name:
      - openssl
      - openssl-pkcs11
      - openssh-server
      - openssh-clients
      - openssh
      - sudo
      - ncurses-libs
      - pam
      - passwd
      - pcre2
      - pcre
      - readline
      - shadow-utils
      - kernel
      - systemd
      - systemd-libs
      - zlib
      - xz
      - filesystem
      - unzip
      - xfsprogs
      - expat-devel
      - openssl-devel
    state: latest
