---
- name: populate service facts
  ansible.builtin.service_facts:

- name: Stop/Disable the service if it's defined
  ansible.builtin.systemd:
    name: "{{ service }}"
    state: stopped
    enabled: no
  loop: "{{ services_list }}"
  loop_control:
    loop_var: service
  when: "ansible_facts.services[service] is defined"

# - name: Stop service firewalld, if running
#   ansible.builtin.systemd:
#     name: firewalld
#     state: stopped

# - name: be sure firewalld is disabled
#   ansible.builtin.systemd: 
#     name: firewalld 
#     enabled: no

# - name: Stop/Disabled service nis-domainname 
#   block:
#     - name: Stop a service of nis-domainname
#       ansible.builtin.systemd: 
#         name: nis-domainname
#         state: stopped
#     - name: Disable a service of nis-domainname
#       ansible.builtin.systemd: 
#         name: nis-domainname
#         enabled: no

# To disable auto update for that is to uninstall packagekit
- name: uninstall packagekit
  dnf:
    name: Packagekit*
    state: absent

- name: Disabling SELinux state
  ansible.posix.selinux:
    state: disabled
  register: selinuxdisabled

- name: Print the changes in Configuration file
  command: grep SELINUX /etc/sysconfig/selinux
  register: selvalue

- name: Print debug message
  debug: 
    var: selvalue.stdout_lines

- name: Install the latest version of security package
  dnf:
    name:
      - openssl
      - openssl-pkcs11
      - openssh-server
      - openssh-clients
      - openssh
      - sudo
      - ncurses-libs
      - pam
      - passwd
      - pcre2
      - pcre
      - readline
      - shadow-utils
      - kernel
      - systemd
      - systemd-libs
      - systemd-pam
      - systemd-udev
      - zlib
      - xz
      - filesystem
      - unzip
      - xfsprogs
    state: latest

- name: Download package only
  block:
    - name: Make directory to store package for nginx
      file:
        path: /root/nginx
        state: directory
    - name: Download only to nginx
      dnf:
        name: nginx
        download_dir: /root/nginx
        download_only: yes
    - name: Make directory to store package for openjdk
      file:
        path: /root/openjdk
        state: directory
    - name: Download only to openjdk
      dnf:
        name: java-1.8.0-openjdk-headless
        download_dir: /root/openjdk
        download_only: yes
    - name: Make a directory to store a package for tomcat
      file:
        path: /root/tomcat
        state: directory
    - name: Download a tomcat 9
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz
        dest: /root/tomcat
