---
- name: populate service facts
  ansible.builtin.service_facts:

- name: Stop/Disable the service if it's defined
  ansible.builtin.systemd:
    name: "{{ service }}"
    state: stopped
    enabled: no
  loop: "{{ stop_services_list }}"
  loop_control:
    loop_var: service
  when: "ansible_facts.services[service] is defined"

- name: Check a process of a server
  shell: pgrep {{ service|lower }} | wc -l
  ignore_errors: false
  changed_when: false
  register: command_result
  failed_when: command_result.stdout|int > 0
  loop: "{{ check_service }}"
  loop_control:
    loop_var: service

- name: Gather the rpm package facts
  package_facts:
    manager: auto

- name: Print the rpm package facts
  debug:
    var: ansible_facts.packages

# To disable auto update for that is to uninstall packagekit
- name: uninstall a package if it's installed
  dnf:
    name: "{{ package }}"
    state: absent
  loop: "{{ uninstall_pacakges }}"
  loop_control:
    loop_var: package
  when: "package in ansible_facts.packages"

- name: Disabling SELinux state
  ansible.posix.selinux:
    state: disabled
  register: selinuxdisabled

- name: Print the changes in Configuration file
  command: grep SELINUX /etc/sysconfig/selinux
  register: selvalue

- name: Print debug message
  debug: 
    var: selvalue.stdout_lines

- name: Install the latest version of security package
  dnf:
    name:
      - openssl
      - openssl-pkcs11
      - openssh-server
      - openssh-clients
      - openssh
      - sudo
      - ncurses-libs
      - pam
      - passwd
      - pcre2
      - pcre
      - readline
      - shadow-utils
      - kernel
      - systemd
      - systemd-libs
      - systemd-pam
      - systemd-udev
      - zlib
      - xz
      - filesystem
      - unzip
      - xfsprogs
    state: latest

- name: Download package only
  block:
    - name: Make directory to store package for nginx
      file:
        path: /root/nginx
        state: directory
    - name: Download only to nginx
      dnf:
        name: nginx
        download_dir: /root/nginx
        download_only: yes
    - name: Make directory to store package for openjdk
      file:
        path: /root/openjdk
        state: directory
    - name: Download only to openjdk
      dnf:
        name: java-1.8.0-openjdk-headless
        download_dir: /root/openjdk
        download_only: yes
    - name: Make a directory to store a package for tomcat
      file:
        path: /root/tomcat
        state: directory
    - name: Download a tomcat 9
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz
        dest: /root/tomcat
