---
- name: Stop service firewalld, if running
  ansible.builtin.systemd:
    name: firewalld
    state: stopped

- name: be sure firewalld is disabled
  ansible.builtin.systemd: 
    name: firewalld 
    enabled: no
    masked: yes

# To disable auto update for that is to uninstall packagekit
- name: uninstall packagekit
  dnf:
    name: Packagekit*
    state: absent

- name: Disabling SELinux state
  ansible.posix.selinux:
    state: disabled
  register: selinuxdisabled

- name: Print the changes in Configuration file
  command: grep SELINUX /etc/sysconfig/selinux
  register: selvalue

- name: Print debug message
  debug: 
    var: selvalue.stdout_lines

- name: Install the latest version of security package
  dnf:
    name:
      - openssl
      - openssl-pkcs11
      - openssh-server
      - openssh-clients
      - openssh
      - sudo
      - ncurses-libs
      - pam
      - passwd
      - pcre2
      - pcre
      - readline
      - shadow-utils
      - kernel
      - systemd
      - systemd-libs
      - systemd-pam
      - systemd-udev
      - zlib
      - xz
      - filesystem
      - unzip
      - xfsprogs
    state: latest
