---
- name: Stop service firewalld, if running
  ansible.builtin.systemd:
    name: firewalld
    state: stopped 

- name: be sure firewalld is disabled
  ansible.builtin.systemd: 
    name: firewalld 
    enabled: no
    masked: yes

- name: Disabling SELinux state
  ansible.posix.selinux:
    state: disabled
  register: selinuxdisabled

- name: Print the changes in Configuration file
  command: grep SELINUX /etc/sysconfig/selinux
  register: selvalue

- name: Print debug message
  debug: 
    var: selvalue.stdout_lines

- name: Copy sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
  notify:
    - Restart sshd