---
- name: include distribution specific task
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"

- name: Download package only
  block:
    - name: Make a directory to store a package for tomcat
      file:
        path: /root/tomcat
        state: directory
    - name: Download a tomcat 9
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz
        dest: /root/tomcat
    - name: Copy a apr library to a tomcat
      ansible.builtin.copy:
        src: apr-1.7.0.rhel8.2.bin.tar.gz
        dest: /root/tomcat
    - name: Copy a apr-utils library to a tomcat
      ansible.builtin.copy:
        src: apr-util-1.6.1.rhel8.2.bin.tar.gz
        dest: /root/tomcat