---
# https://access.redhat.com/solutions/5027331
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/chap-hardening_your_system_with_tools_and_services
# /etc/pam.d/password-auth 에 pam_pwquality.so 설정이 되어 있다. 
# 패스워드 복잡도 설정은 /etc/security/pwquality.conf 에 설정을 한다.
# root 계정에 대한 패스워드 복잡도는 설정이 적용되지 않음.
- name: Copy a file to a password's strength against a set of rules.
  copy:
    src: pwquality.conf
    dest: /etc/security/pwquality.conf

- name: Copy a file to a login's fails against a set of rules.
  copy:
    src: faillock.conf
    dest: /etc/security/faillock.conf

- name: backup system-auth
  copy:
    src: /etc/pam.d/system-auth
    dest: /etc/pam.d/system-auth_{{ansible_date_time.date}}@{{ansible_date_time.time}}.bkp
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
    force: yes
  tags:
    - system-auth-backup

- name: backup password-auth
  copy:
    src: /etc/pam.d/password-auth
    dest: /etc/pam.d/password-auth_{{ansible_date_time.date}}@{{ansible_date_time.time}}.bkp
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
    force: yes
  tags:
    - system-auth-backup

- name: Keep history of used passwords (the number of previous passwords which cannot be reused) - system-auth.
  community.general.pamd:
    name: system-auth
    type: password
    control: requisite
    module_path: pam_pwquality.so
    new_type: password
    new_control: requisite
    new_module_path: pam_pwhistory.so
    module_arguments: 'remember=5
        use_authtok'
    state: after

- name: Keep history of used passwords (the number of previous passwords which cannot be reused) - password-auth.
  community.general.pamd:
    name: password-auth
    type: password
    control: requisite
    module_path: pam_pwquality.so
    new_type: password
    new_control: requisite
    new_module_path: pam_pwhistory.so
    module_arguments: 'remember=5
        use_authtok'
    state: after

- name: faillock preauth - system-auth
  community.general.pamd:
    name: system-auth
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: required
    new_module_path: pam_faillock.so
    module_arguments: 'preauth'
    state: before

- name: faillock preauth - password-auth
  community.general.pamd:
    name: password-auth
    type: auth
    control: sufficient
    module_path: pam_unix.so
    new_type: auth
    new_control: required
    new_module_path: pam_faillock.so
    module_arguments: 'preauth'
    state: before

- name: faillock authfail - system-auth
  community.general.pamd:
    name: system-auth
    type: auth
    control: required
    module_path: pam_deny.so
    new_type: auth
    new_control: required
    new_module_path: pam_faillock.so
    module_arguments: 'authfail'
    state: before

- name: faillock authfail - password-auth
  community.general.pamd:
    name: password-auth
    type: auth
    control: required
    module_path: pam_deny.so
    new_type: auth
    new_control: required
    new_module_path: pam_faillock.so
    module_arguments: 'authfail'
    state: before

- name: faillock account - system-auth
  community.general.pamd:
    name: system-auth
    type: account
    control: required
    module_path: pam_unix.so
    new_type: account
    new_control: required
    new_module_path: pam_faillock.so
    state: before

- name: faillock account - password-auth
  community.general.pamd:
    name: password-auth
    type: account
    control: required
    module_path: pam_unix.so
    new_type: account
    new_control: required
    new_module_path: pam_faillock.so
    state: before

# 패스워드 최대 유효기간 설정. /etc/login.def
- name: Chagne policy for password to /etc/login.def
  tags: login.def
  block:
  - name: Set maximum number of days a password may be used
    lineinfile:
      path: /etc/login.defs
      regexp: '^PASS_MAX_DAYS'
      line: PASS_MAX_DAYS 90

  - name: Set minimum number of days allowed between password changes
    lineinfile:
      path: /etc/login.defs
      regexp: '^PASS_MIN_DAYS'
      line: PASS_MIN_DAYS 1

  - name: Set minimum acceptable password length
    lineinfile:
      path: /etc/login.defs
      regexp: '^PASS_MIN_LEN'
      line: PASS_MIN_LEN 8