---
- name: Remove unnecessary users, groups
  tags: rmUserGroups
  block:
    - name: Remove unnecessary users
      user:
        name: "{{ rmUsers.user_name }}"
        state: absent
      with_items: "{{ remove_user_list }}"
      loop_control:
        loop_var: rmUsers

    - name: Remove unnecessary groups
      group:
        name: "{{ rmGrps.grp_name }}"
        state: absent
      with_items: "{{ remove_group_list }}"
      loop_control:
        loop_var: rmGrps