---
- name: Remove unnecessary users
  user:
    name: "{{ rmUsers.user_name }}"
    state: absent
  with_items: "{{ remove_user_list }}"
  loop_control:
    loop_var: rmUsers

- name: Remove unnecessary groups
  group:
    name: "{{ rmGrps.grp_name }}"
    state: absent
  with_items: "{{ remove_group_list }}"
  loop_control:
    loop_var: rmGrps

- name: Ensure group for system admin
  group:
    name: "{{ newGrps.grp_name }}"
    gid: "{{ newGrps.gid }}"
    state: present
  with_items: "{{ add_sysadm_group }}"
  loop_control:
    loop_var: newGrps

- name: Ensure user for system admin
  user:
    name: "{{ newUsers.user_name }}"
    uid: "{{ newUsers.uid }}"
    password: "{{ newUsers.passwd }}"
    comment: "{{ newUsers.comment }}"
    group: "{{ newUsers.group }}"
    groups: [wheel,]
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    state: present
  with_items: "{{ add_sys_user }}"
  loop_control:
    loop_var: newUsers