---
remove_group_list:
  - grp_name: floppy
  - grp_name: games
  - grp_name: cdrom
  - grp_name: video
  - grp_name: tape
  - grp_name: ftp
  - grp_name: audio
  - grp_name: kvm
  - grp_name: render
  - grp_name: lp
  - grp_name: dialout
  - grp_name: rpc
  - grp_name: postfix
  - grp_name: postdrop
  - grp_name: slocate
  - grp_name: screen
  - grp_name: tcpdump
  - grp_name: utempter

remove_user_list:
  - user_name: ftp
  - user_name: games
  - user_name: operator
  - user_name: lp
  - user_name: tcpdump
  - user_name: postfix
  - user_name: rpc
